import React from 'react';
import { useParams } from 'react-router-dom';
import '../App.css';
import { Images } from '../Pics/Images';
import Twoforall from '../Detaildata/Twoforall';

const Configure = () => {
    const { model1 } = useParams();

    const modelData = {

        flyingSpur: {
            tempbg: Images.spur4,
            title: "Flying Spur",
            description: "Every Flying Spur represents a combination of performance and luxury that should be impossible. Passengers can expect an exquisite, limousine-like experience, characterised by generous legroom.",
            price: "₹4 Crore",
            specifications: [
                { label: "Power Output", value: "542 Hp" },
                { label: "Maximum speed", value: "333 KM/H (207 mph)" },
                { label: "Engine", value: "4.0-liter V8 twin-turbocharged" },
                { label: "Length", value: "5,316 mm" },
                { label: "Width", value: "1,968 mm" },
                { label: "Height", value: "1,488 mm" },
                { label: "Wheelbase", value: "3,194 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "3.8 s" },
                { label: "Torque", value: "770 Nm" },
            ],
            galleryData: [
                { image: Images.spur1 },
                { image: Images.spur2 },
                { image: Images.spur3 },
                { image: Images.spur4 },
                { image: Images.spur5 },
            ],
        },
        continental: {
            tempbg: Images.con2,
            title: "New Continental GT Speed",
            description: "As the Continental GT enters its 21st year, it once again redefines the ultimate blend of supercar performance, handcrafted luxury and everyday usability.",
            price: "₹4 Crore",
            specifications: [
                { label: "Power Output", value: "542 Hp" },
                { label: "Maximum speed", value: "333 KM/H (207 mph)" },
                { label: "Engine", value: "4.0-liter V8 twin-turbocharged" },
                { label: "Length", value: "4,850 mm" },
                { label: "Width", value: "1,964 mm" },
                { label: "Height", value: "1,405 mm" },
                { label: "Wheelbase", value: "2,746 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "3.6 s" },
                { label: "Torque", value: "770 Nm" },
            ],
            galleryData: [
                { image: Images.con1 },
                { image: Images.con2 },
                { image: Images.con3 },
                { image: Images.con4 },
                { image: Images.con5 },
            ],
        },
        mulliner: {
            tempbg: Images.mul3,
            title: "MULLINER",
            description: "Bentley's coachbuilding artisans can bring your perfect car to life. With Mulliner, the possibilities are endless.",
            price: "₹6.95 Crore",
            specifications: [
                { label: "Power Output", value: "542 Hp" },
                { label: "Maximum speed", value: "290 KM/H (155 mph)" },
                { label: "Engine", value: "4.0-liter V8 twin-turbocharged" },
                { label: "Length", value: "5,140 mm" },
                { label: "Width", value: "1,998 mm" },
                { label: "Height", value: "1,742 mm" },
                { label: "Wheelbase", value: "2,995 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "4.5 s" },
                { label: "Torque", value: "800 Nm" },
            ],
            galleryData: [
                { image: Images.mul1 },
                { image: Images.mul2 },
                { image: Images.mul3 },
                { image: Images.mul4 },
                { image: Images.mul5 },
            ],
        },
        bentayga: {
            tempbg: Images.ben3,
            title: "BENTAYGA",
            description: "The Bentayga EWB sets new standards in SUV comfort. This stunning Bentley long wheelbase vehicle combines cutting-edge technology with head-turning road presence and a 4.0 litre V8 engine.",
            price: "₹6 Crore",
            specifications: [
                { label: "Power Output", value: "542 Hp" },
                { label: "Maximum speed", value: "290 KM/H (155 mph)" },
                { label: "Engine", value: "4.0-liter V8 twin-turbocharged" },
                { label: "Length", value: "5,450 mm" },
                { label: "Width", value: "2,198 mm" },
                { label: "Height", value: "1,742 mm" },
                { label: "Wheelbase", value: "3,175 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "4.5 s" },
                { label: "Torque", value: "770 Nm" },
            ],
            galleryData: [
                { image: Images.ben1 },
                { image: Images.ben2 },
                { image: Images.ben3 },
                { image: Images.ben4 },
                { image: Images.ben5 },
            ],
        },
        cilindri: {
            tempbg: Images.cili4,
            title: "12 Cilindri",
            description: '"A masterpiece of engineering that defines the essence of speed and luxury. The Ferrari 12 Cilindri is not just a car; it\'s an experience."',
            price: "₹3.0 Crore",
            specifications: [
                { label: "Power Output", value: "800 hp" },
                { label: "Maximum speed", value: "340 KM/H (211 mph)" },
                { label: "Engine", value: "6.5-liter V12" },
                { label: "Length", value: "4,657 mm" },
                { label: "Width", value: "1,971 mm" },
                { label: "Height", value: "1,273 mm" },
                { label: "Wheelbase", value: "2,747 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "2.9 s" },
                { label: "Torque", value: "718 Nm" },
            ],
            galleryData: [
                { image: Images.cili1 },
                { image: Images.cili2 },
                { image: Images.cili3 },
                { image: Images.cili4 },
                { image: Images.cili5 },
            ],
        },
        gts: {
            tempbg: Images.gts2,
            title: "296 GTS",
            description: '"Performance meets elegance in a symphony of power."',
            price: "₹6.24 Crore",
            specifications: [
                { label: "Power Output", value: "818 hp" },
                { label: "Maximum speed", value: "330 KM/H (205 mph)" },
                { label: "Engine", value: "3.0-liter V6 twin-turbocharged + electric motor" },
                { label: "Length", value: "4,610 mm" },
                { label: "Width", value: "1,978 mm" },
                { label: "Height", value: "1,190 mm" },
                { label: "Wheelbase", value: "2,600 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "2.9 s" },
                { label: "Torque", value: "740 Nm" },
            ],
            galleryData: [
                { image: Images.gts1 },
                { image: Images.gts2 },
                { image: Images.gts3 },
                { image: Images.gts4 },
                { image: Images.gts5 },
            ],
        },
        daytona: {
            tempbg: Images.ds35,
            title: "Daytona SP3",
            description: '"A tribute to the glorious past, the Daytona SP3 redefines modern performance."',
            price: "₹9.5 Crore",
            specifications: [
                { label: "Power Output", value: "840 hp" },
                { label: "Maximum speed", value: "340 KM/H (211 mph)" },
                { label: "Engine", value: "6.5-liter V12 naturally aspirated" },
                { label: "Length", value: "4,600 mm" },
                { label: "Width", value: "2,020 mm" },
                { label: "Height", value: "1,140 mm" },
                { label: "Wheelbase", value: "2,650 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "2.9 s" },
                { label: "Torque", value: "710 Nm" },
            ],
            galleryData: [
                { image: Images.ds31 },
                { image: Images.ds32 },
                { image: Images.ds33 },
                { image: Images.ds34 },
                { image: Images.ds35 },
            ],
        },
        laferrari: {
            tempbg: Images.laf5,
            title: "LaFerrari",
            description: '"The LaFerrari is not just a car; it’s a masterpiece of engineering and design."',
            price: "₹15 Crore",
            specifications: [
                { label: "Power Output", value: "950 hp" },
                { label: "Maximum speed", value: "352 KM/H (218 mph)" },
                { label: "Engine", value: "6.3-liter V12 + electric motor" },
                { label: "Length", value: "4,702 mm" },
                { label: "Width", value: "1,992 mm" },
                { label: "Height", value: "1,116 mm" },
                { label: "Wheelbase", value: "2,650 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "2.6 s" },
                { label: "Torque", value: "900 Nm" },
            ],
            galleryData: [
                { image: Images.laf1 },
                { image: Images.laf2 },
                { image: Images.laf3 },
                { image: Images.laf4 },
                { image: Images.laf5 },
            ],
        },
        boatail: {
            tempbg: Images.boat5,
            title: "BOAT TAIL",
            description: "Boat Tail is our most ambitious project yet. Coachbuild, in collaboration with its clients, has ignored all preconceived notions of possibility and set a new standard. This is Bespoke at its purest.",
            price: "₹200 Crore",
            specifications: [
                { label: "Power Output", value: "563 hp" },
                { label: "Maximum speed", value: "250 KM/H (155 mph)" },
                { label: "Engine", value: "6.75-liter V12 twin-turbocharged" },
                { label: "Length", value: "5,800 mm" },
                { label: "Width", value: "1,998 mm" },
                { label: "Height", value: "1,500 mm" },
                { label: "Wheelbase", value: "3,200 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "4.6 s" },
                { label: "Torque", value: "850 Nm" },
            ],
            galleryData: [
                { image: Images.boat1 },
                { image: Images.boat2 },
                { image: Images.boat3 },
                { image: Images.boat4 },
                { image: Images.boat5 },
            ],
        },
        ghost: {
            tempbg: Images.bgh4,
            title: "BLACK BADGE GHOST",
            description: "Black Badge Ghost lives after dark, igniting the rebel within. Powerful, agile, and fearless, it is the most potent manifestation of Rolls-Royce yet — a drive defined by unrelenting force and finesse.",
            price: "₹12.25 Crore",
            specifications: [
                { label: "Power Output", value: "603 hp" },
                { label: "Maximum speed", value: "250 KM/H (155 mph)" },
                { label: "Engine", value: "6.75-liter V12 twin-turbocharged" },
                { label: "Length", value: "5,546 mm" },
                { label: "Width", value: "1,998 mm" },
                { label: "Height", value: "1,550 mm" },
                { label: "Wheelbase", value: "3,295 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "4.6 s" },
                { label: "Torque", value: "900 Nm" },
            ],
            galleryData: [
                { image: Images.bgh1 },
                { image: Images.bgh2 },
                { image: Images.bgh3 },
                { image: Images.bgh4 },
                { image: Images.bgh5 },
            ],
        },
        phantom: {
            tempbg: Images.pa3,
            title: "PHANTOM",
            description: "A HAVEN OF SERENITY AWAITS. PHANTOM EXTENDED.",
            price: "₹10.48 Crore",
            specifications: [
                { label: "Power Output", value: "563 hp" },
                { label: "Maximum speed", value: "250 KM/H (155 mph)" },
                { label: "Engine", value: "6.75-liter V12 twin-turbocharged" },
                { label: "Length", value: "5,762 mm" },
                { label: "Width", value: "1,998 mm" },
                { label: "Height", value: "1,570 mm" },
                { label: "Wheelbase", value: "3,552 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "5.3 s" },
                { label: "Torque", value: "900 Nm" },
            ],
            galleryData: [
                { image: Images.pa1 },
                { image: Images.pa2 },
                { image: Images.pa3 },
                { image: Images.pa4 },
                { image: Images.pa5 },
            ],
        },
        cullinan: {
            tempbg: Images.cul5,
            title: "CULLINAN",
            description: "A powerful presence with endless capabilities, Cullinan Series II belongs to the invincible.",
            price: "₹6.95 Crore",
            specifications: [
                { label: "Power Output", value: "563 hp" },
                { label: "Maximum speed", value: "250 KM/H (155 mph)" },
                { label: "Engine", value: "6.75-liter V12 twin-turbocharged" },
                { label: "Length", value: "5,341 mm" },
                { label: "Width", value: "2,000 mm" },
                { label: "Height", value: "1,835 mm" },
                { label: "Wheelbase", value: "3,295 mm" },
                { label: "0 - 100 KM/H (62 mph)", value: "5.0 s" },
                { label: "Torque", value: "850 Nm" },
            ],
            galleryData: [
                { image: Images.cul1 },
                { image: Images.cul2 },
                { image: Images.cul3 },
                { image: Images.cul4 },
                { image: Images.cul5 },
            ],
        },
        scrambler1100: {
            tempbg: Images.scr3,
            title: "Scrambler 1100",
            description: "Retro spirit with modern performance—perfect for everyday adventures.",
            price: "₹13.75 Lakh",
            specifications: [
                { label: "Engine", value: "1,079 cc L-twin" },
                { label: "Fuel Capacity", value: "15 liters" },
                { label: "Torque", value: "88 Nm" },
                { label: "Max Speed", value: "205 KM/H (127 mph)" },
                { label: "Weight", value: "206 kg" },
                { label: "Wheel Base", value: "1,514 mm" },
                { label: "Wheels", value: "18\"/17\" (Front/Rear)" },
                { label: "Output", value: "86 hp" },
            ],
            galleryData: [
                { image: Images.scr1 },
                { image: Images.scr2 },
                { image: Images.scr3 },
                { image: Images.scr4 },
                { image: Images.scr5 },
            ],
        },
        panigalev4: {
            tempbg: Images.pan3,
            title: "Panigale V4",
            description: "A purebred racing machine—track performance for the road.",
            price: "₹26.49 Lakhs",
            specifications: [
                { label: "Engine", value: "1,103 cc V4" },
                { label: "Fuel Capacity", value: "16 liters" },
                { label: "Torque", value: "124 Nm" },
                { label: "Max Speed", value: "299+ KM/H (186+ mph)" },
                { label: "Weight", value: "198 kg" },
                { label: "Wheel Base", value: "1,469 mm" },
                { label: "Wheels", value: "17\"/17\" (Front/Rear)" },
                { label: "Output", value: "214 hp" },
            ],
            galleryData: [
                { image: Images.pan1 },
                { image: Images.pan2 },
                { image: Images.pan3 },
                { image: Images.pan4 },
                { image: Images.pan5 },
            ],
        },
        monster: {
            tempbg: Images.mon3,
            title: "Monster",
            description: "Lightweight, powerful, and agile—the Monster redefines naked sport riding.",
            price: "₹12.49 Crore",
            specifications: [
                { label: "Engine", value: "937 cc L-twin" },
                { label: "Fuel Capacity", value: "14 liters" },
                { label: "Torque", value: "93 Nm" },
                { label: "Max Speed", value: "240 KM/H (149 mph)" },
                { label: "Weight", value: "188 kg" },
                { label: "Wheel Base", value: "1,474 mm" },
                { label: "Wheels", value: "17\"/17\" (Front/Rear)" },
                { label: "Output", value: "111 hp" },
            ],
            galleryData: [
                { image: Images.mon1 },
                { image: Images.mon2 },
                { image: Images.mon3 },
                { image: Images.mon4 },
                { image: Images.mon5 },
            ],
        },
        diavel1260: {
            tempbg: Images.dia2,
            title: "Diavel V4",
            description: "A bold statement in power, technology, and design—an uncompromising cruiser with sports bike DNA.",
            price: "₹21.49 Crore",
            specifications: [
                { label: "Engine", value: "1,262 cc L-twin" },
                { label: "Fuel Capacity", value: "17 liters" },
                { label: "Torque", value: "129 Nm" },
                { label: "Max Speed", value: "270 KM/H (168 mph)" },
                { label: "Weight", value: "218 kg" },
                { label: "Wheel Base", value: "1,600 mm" },
                { label: "Wheels", value: "17\"/17\" (Front/Rear)" },
                { label: "Output", value: "159 hp" },
            ],
            galleryData: [
                { image: Images.dia1 },
                { image: Images.dia2 },
                { image: Images.dia3 },
                { image: Images.dia4 },
                { image: Images.dia5 },
            ],
        },
        x440: {
            tempbg: Images.x4402,
            title: "X™ 440",
            description: "Classic styling meets modern performance in a bike designed for urban adventure.",
            price: "₹2.29 Lakhs",
            specifications: [
                { label: "Engine", value: "440 cc Single-Cylinder" },
                { label: "Fuel Capacity", value: "12 liters" },
                { label: "Torque", value: "38 Nm" },
                { label: "Max Speed", value: "150 KM/H (93 mph)" },
                { label: "Weight", value: "178 kg" },
                { label: "Wheel Base", value: "1,400 mm" },
                { label: "Wheels", value: "17\"/17\" (Front/Rear)" },
                { label: "Output", value: "27 hp" },
            ],
            galleryData: [
                { image: Images.x4401 },
                { image: Images.x4402 },
                { image: Images.x4403 },
                { image: Images.x4404 },
                { image: Images.x4405 },
            ],
        },
        sportster: {
            tempbg: Images.spo2,
            title: "Sportster™ S",
            description: "A modern take on the iconic Sportster, delivering power and agility for the urban rider.",
            price: "₹15.51 Lakhs",
            specifications: [
                { label: "Engine", value: "1,250 cc V-twin" },
                { label: "Fuel Capacity", value: "11.8 liters" },
                { label: "Torque", value: "125 Nm" },
                { label: "Max Speed", value: "200 KM/H (124 mph)" },
                { label: "Weight", value: "228 kg" },
                { label: "Wheel Base", value: "1,495 mm" },
                { label: "Wheels", value: "19\"/16\" (Front/Rear)" },
                { label: "Output", value: "121 hp" },
            ],
            galleryData: [
                { image: Images.spo1 },
                { image: Images.spo2 },
                { image: Images.spo3 },
                { image: Images.spo4 },
                { image: Images.spo5 },
            ],
        },
        glide: {
            tempbg: Images.gli4,
            title: "Road Glide",
            description: "Ride the open road with confidence, style, and power at your fingertips.",
            price: "₹41.79 Lakhs",
            specifications: [
                { label: "Engine", value: "1,868 cc V-twin" },
                { label: "Fuel Capacity", value: "22.7 liters" },
                { label: "Torque", value: "163 Nm" },
                { label: "Max Speed", value: "200 KM/H (124 mph)" },
                { label: "Weight", value: "400 kg" },
                { label: "Wheel Base", value: "1,625 mm" },
                { label: "Wheels", value: "19\"/16\" (Front/Rear)" },
                { label: "Output", value: "93 hp" },
            ],
            galleryData: [
                { image: Images.gli1 },
                { image: Images.gli2 },
                { image: Images.gli3 },
                { image: Images.gli4 },
                { image: Images.gli5 },
            ],
        },
        breakout: {
            tempbg: Images.bo2,
            title: "Breakout™ 117",
            description: "The perfect blend of power and style, built for those who crave the open road.",
            price: "₹24.99 Lakhs",
            specifications: [
                { label: "Engine", value: "1,923 cc V-twin" },
                { label: "Fuel Capacity", value: "18.9 liters" },
                { label: "Torque", value: "165 Nm" },
                { label: "Max Speed", value: "180 KM/H (112 mph)" },
                { label: "Weight", value: "295 kg" },
                { label: "Wheel Base", value: "1,630 mm" },
                { label: "Wheels", value: "21\"/18\" (Front/Rear)" },
                { label: "Output", value: "93 hp" },
            ],
            galleryData: [
                { image: Images.bo1 },
                { image: Images.bo2 },
                { image: Images.bo3 },
                { image: Images.bo4 },
                { image: Images.bo5 },
            ],
        },
        elite: {
            tempbg: Images.ce5,
            title: "Challenger Elite",
            description: "The Indian Challenger Elite combines power and style for an unmatched riding experience.",
            price: "₹39.99 Lakhs",
            specifications: [
                { label: "Engine", value: "1,768 cc V-twin" },
                { label: "Fuel Capacity", value: "20.0 liters" },
                { label: "Torque", value: "178 Nm" },
                { label: "Max Speed", value: "200 KM/H (124 mph)" },
                { label: "Weight", value: "305 kg" },
                { label: "Wheel Base", value: "1,610 mm" },
                { label: "Wheels", value: "19\"/16\" (Front/Rear)" },
                { label: "Output", value: "122 hp" },
            ],
            galleryData: [
                { image: Images.ce1 },
                { image: Images.ce2 },
                { image: Images.ce3 },
                { image: Images.ce4 },
                { image: Images.ce5 },
            ],
        },
        bobber: {
            tempbg: Images.sco3,
            title: "Scout Bobber Twenty",
            description: "Old-school styling meets modern power, creating a ride that is as thrilling as it is timeless.",
            price: "₹16.48 Lakhs",
            specifications: [
                { label: "Engine", value: "1,133 cc V-twin" },
                { label: "Fuel Capacity", value: "12.5 liters" },
                { label: "Torque", value: "98 Nm" },
                { label: "Max Speed", value: "185 KM/H (115 mph)" },
                { label: "Weight", value: "255 kg" },
                { label: "Wheel Base", value: "1,576 mm" },
                { label: "Wheels", value: "16\"/16\" (Front/Rear)" },
                { label: "Output", value: "100 hp" },
            ],
            galleryData: [
                { image: Images.sco1 },
                { image: Images.sco2 },
                { image: Images.sco3 },
                { image: Images.sco4 },
                { image: Images.sco5 },
            ],
        },
        ftrx: {
            tempbg: Images.ftr3,
            title: "FTR X RSD Super Hooligan",
            description: "The FTR X RSD Super Hooligan is designed for those who live on the edge of performance.",
            price: "₹18 Lakhs",
            specifications: [
                { label: "Engine", value: "1,203 cc V-twin" },
                { label: "Fuel Capacity", value: "13.2 liters" },
                { label: "Torque", value: "120 Nm" },
                { label: "Max Speed", value: "200 KM/H (124 mph)" },
                { label: "Weight", value: "221 kg" },
                { label: "Wheel Base", value: "1,489 mm" },
                { label: "Wheels", value: "19\"/18\" (Front/Rear)" },
                { label: "Output", value: "120 hp" },
            ],
            galleryData: [
                { image: Images.ftr1 },
                { image: Images.ftr2 },
                { image: Images.ftr3 },
                { image: Images.ftr4 },
                { image: Images.ftr5 },
            ],
        },
        chief: {
            tempbg: Images.dar3,
            title: "Chief Bobber Dark Horse",
            description: "Embrace the road ahead with power, style, and an undeniable presence.",
            price: "₹20.10 Lakhs",
            specifications: [
                { label: "Engine", value: "1,890 cc V-twin" },
                { label: "Fuel Capacity", value: "15.1 liters" },
                { label: "Torque", value: "162 Nm" },
                { label: "Max Speed", value: "185 KM/H (115 mph)" },
                { label: "Weight", value: "299 kg" },
                { label: "Wheel Base", value: "1,596 mm" },
                { label: "Wheels", value: "16\"/16\" (Front/Rear)" },
                { label: "Output", value: "92 hp" },
            ],
            galleryData: [
                { image: Images.dar1 },
                { image: Images.dar2 },
                { image: Images.dar3 },
                { image: Images.dar4 },
                { image: Images.dar5 },
            ],
        },
        scram: {
            tempbg: Images.sc45,
            title: "Scram 411",
            description: "Designed for the urban explorer, the Scram 411 offers the versatility to conquer any terrain with ease.",
            price: "₹2.03 Lakhs",
            specifications: [
                { label: "Engine", value: "411 cc Single Cylinder, Air-Cooled" },
                { label: "Fuel Capacity", value: "15 liters" },
                { label: "Torque", value: "32 Nm" },
                { label: "Max Speed", value: "125 KM/H (78 mph)" },
                { label: "Weight", value: "185 kg" },
                { label: "Wheel Base", value: "1,455 mm" },
                { label: "Wheels", value: "19\"/17\" (Front/Rear)" },
                { label: "Output", value: "24 hp" },
            ],
            galleryData: [
                { image: Images.sc41 },
                { image: Images.sc42 },
                { image: Images.sc43 },
                { image: Images.sc44 },
                { image: Images.sc45 },
            ],
        },
        himalayan: {
            tempbg: Images.him3,
            title: "Himalayan 450",
            description: "Built for the adventurer, the Himalayan 450 takes you anywhere, from rugged trails to city streets.",
            price: "₹2.80 Lakhs",
            specifications: [
                { label: "Engine", value: "450 cc Single Cylinder, Liquid-Cooled" },
                { label: "Fuel Capacity", value: "15 liters" },
                { label: "Torque", value: "40 Nm" },
                { label: "Max Speed", value: "140 KM/H (87 mph)" },
                { label: "Weight", value: "210 kg" },
                { label: "Wheel Base", value: "1,465 mm" },
                { label: "Wheels", value: "21\"/17\" (Front/Rear)" },
                { label: "Output", value: "40 hp" },
            ],
            galleryData: [
                { image: Images.him1 },
                { image: Images.him2 },
                { image: Images.him3 },
                { image: Images.him4 },
                { image: Images.him5 },
            ],
        },
        contgt: {
            tempbg: Images.gtc5,
            title: "Continental GT 650",
            description: "Classic café racer styling with modern performance—built for the pure motorcycling enthusiast.",
            price: "₹3.14 Lakhs",
            specifications: [
                { label: "Engine", value: "648 cc Parallel Twin" },
                { label: "Fuel Capacity", value: "12.5 liters" },
                { label: "Torque", value: "52 Nm" },
                { label: "Max Speed", value: "160 KM/H (99 mph)" },
                { label: "Weight", value: "198 kg" },
                { label: "Wheel Base", value: "1,400 mm" },
                { label: "Wheels", value: "18\"/18\" (Front/Rear)" },
                { label: "Output", value: "47 hp" },
            ],
            galleryData: [
                { image: Images.gtc1 },
                { image: Images.gtc2 },
                { image: Images.gtc3 },
                { image: Images.gtc4 },
            ],
        },
        bullet: {
            tempbg: Images.bul3,
            title: "Bullet 350",
            description: "A timeless classic that defines a legacy of endurance, charm, and vintage appeal.",
            price: "₹1.73 Lakhs",
            specifications: [
                { label: "Engine", value: "346 cc Single Cylinder, Air-Cooled" },
                { label: "Fuel Capacity", value: "13.5 liters" },
                { label: "Torque", value: "28 Nm" },
                { label: "Max Speed", value: "110 KM/H (68 mph)" },
                { label: "Weight", value: "191 kg" },
                { label: "Wheel Base", value: "1,370 mm" },
                { label: "Wheels", value: "19\"/19\" (Front/Rear)" },
                { label: "Output", value: "19.1 hp" },
            ],
            galleryData: [
                { image: Images.bul1 },
                { image: Images.bul2 },
                { image: Images.bul3 },
                { image: Images.bul4 },
                { image: Images.bul5 },
            ],
        },



    };

    const currentModel = modelData[model1.toLowerCase()] || modelData.flyingSpur;

    return (

        <Twoforall
            tempbg={currentModel.tempbg}
            title={currentModel.title}
            description={currentModel.description}
            price={currentModel.price}
            specifications={currentModel.specifications}
            galleryData={currentModel.galleryData}
        />
    );
};

export default Configure;
